language: java
sudo: false

jdk:
  - oraclejdk8
services:
  - mysql

before_install:
  - chmod -R 777 ./travis/before_install.sh
  - ./travis/before_install.sh

install:
  # Compile sources with Java 1.8
  - jdk_switcher use oraclejdk8
  - chmod -R 777 ./travis/install.sh
  - ./travis/install.sh

#script:
#  - jdk_switcher use oraclejdk8
#  - chmod -R 777 ./travis/package.sh
#  - ./travis/package.sh