language: java
sudo: false

jdk:
  - oraclejdk8

install:
  # Compile sources with Java 1.8
  - jdk_switcher use oraclejdk8
  - chmod -R 777 ./travis/install.sh
  - ./travis/install.sh
  # Switch back to the original JDK to run the tests
  - jdk_switcher use ${TRAVIS_JDK_VERSION}