language: java
sudo: required

jdk:
  - oraclejdk8

dist: trusty

services:
  - mysql

addons:
  sonarqube

before_install:
  # Build DB dependency for testd
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sapphire;'
  - chmod -R 777 input.sql

  - mysql -e 'source input.sql'

install:
  # Compile sources with Java 1.8
  - jdk_switcher use oraclejdk8
  - chmod -R 777 ./travis/install.sh
  - ./travis/install.sh

script:
  - jdk_switcher use oraclejdk8
  - chmod -R 777 ./travis/package.sh
  - ./travis/package.sh
